/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FarmerRouteImport } from './routes/farmer'
import { Route as BuyerRouteImport } from './routes/buyer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingFarmerRouteImport } from './routes/onboarding.farmer'
import { Route as OnboardingBuyerRouteImport } from './routes/onboarding.buyer'
import { Route as FarmerStorefrontRouteImport } from './routes/farmer.storefront'
import { Route as FarmerSettingsRouteImport } from './routes/farmer.settings'
import { Route as FarmerPricesRouteImport } from './routes/farmer.prices'
import { Route as FarmerPremiumRouteImport } from './routes/farmer.premium'
import { Route as FarmerOrdersRouteImport } from './routes/farmer.orders'
import { Route as FarmerOffersRouteImport } from './routes/farmer.offers'
import { Route as FarmerJournalRouteImport } from './routes/farmer.journal'
import { Route as FarmerHomeRouteImport } from './routes/farmer.home'
import { Route as FarmerCommunityRouteImport } from './routes/farmer.community'
import { Route as FarmerBillingRouteImport } from './routes/farmer.billing'
import { Route as FarmerAnalyticsRouteImport } from './routes/farmer.analytics'
import { Route as BuyerSubscriptionsRouteImport } from './routes/buyer.subscriptions'
import { Route as BuyerReportsRouteImport } from './routes/buyer.reports'
import { Route as BuyerPaymentRouteImport } from './routes/buyer.payment'
import { Route as BuyerOrdersRouteImport } from './routes/buyer.orders'
import { Route as BuyerMessagesRouteImport } from './routes/buyer.messages'
import { Route as BuyerDiscoverRouteImport } from './routes/buyer.discover'
import { Route as BuyerAccountRouteImport } from './routes/buyer.account'
import { Route as FarmerJournalIndexRouteImport } from './routes/farmer.journal.index'
import { Route as FarmerSettingsNotifsRouteImport } from './routes/farmer.settings.notifs'
import { Route as FarmerJournalNewRouteImport } from './routes/farmer.journal.new'
import { Route as FarmerJournalEntryIdRouteImport } from './routes/farmer.journal.$entryId'
import { Route as BuyerSubscriptionProducerIdRouteImport } from './routes/buyer.subscription.$producerId'
import { Route as BuyerProducerIdRouteImport } from './routes/buyer.producer.$id'
import { Route as BuyerOrdersOrderIdRouteImport } from './routes/buyer.orders.$orderId'
import { Route as BuyerOfferListingIdRouteImport } from './routes/buyer.offer.$listingId'
import { Route as BuyerNegotiationOfferIdRouteImport } from './routes/buyer.negotiation.$offerId'
import { Route as FarmerOrdersOfferIdCounterRouteImport } from './routes/farmer.orders.$offerId.counter'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerRoute = FarmerRouteImport.update({
  id: '/farmer',
  path: '/farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerRoute = BuyerRouteImport.update({
  id: '/buyer',
  path: '/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingFarmerRoute = OnboardingFarmerRouteImport.update({
  id: '/onboarding/farmer',
  path: '/onboarding/farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingBuyerRoute = OnboardingBuyerRouteImport.update({
  id: '/onboarding/buyer',
  path: '/onboarding/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerStorefrontRoute = FarmerStorefrontRouteImport.update({
  id: '/storefront',
  path: '/storefront',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerSettingsRoute = FarmerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerPricesRoute = FarmerPricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerPremiumRoute = FarmerPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerOrdersRoute = FarmerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerOffersRoute = FarmerOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerJournalRoute = FarmerJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerHomeRoute = FarmerHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerCommunityRoute = FarmerCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerBillingRoute = FarmerBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerAnalyticsRoute = FarmerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => FarmerRoute,
} as any)
const BuyerSubscriptionsRoute = BuyerSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerReportsRoute = BuyerReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerPaymentRoute = BuyerPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerOrdersRoute = BuyerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerMessagesRoute = BuyerMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerDiscoverRoute = BuyerDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerAccountRoute = BuyerAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => BuyerRoute,
} as any)
const FarmerJournalIndexRoute = FarmerJournalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FarmerJournalRoute,
} as any)
const FarmerSettingsNotifsRoute = FarmerSettingsNotifsRouteImport.update({
  id: '/notifs',
  path: '/notifs',
  getParentRoute: () => FarmerSettingsRoute,
} as any)
const FarmerJournalNewRoute = FarmerJournalNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => FarmerJournalRoute,
} as any)
const FarmerJournalEntryIdRoute = FarmerJournalEntryIdRouteImport.update({
  id: '/$entryId',
  path: '/$entryId',
  getParentRoute: () => FarmerJournalRoute,
} as any)
const BuyerSubscriptionProducerIdRoute =
  BuyerSubscriptionProducerIdRouteImport.update({
    id: '/subscription/$producerId',
    path: '/subscription/$producerId',
    getParentRoute: () => BuyerRoute,
  } as any)
const BuyerProducerIdRoute = BuyerProducerIdRouteImport.update({
  id: '/producer/$id',
  path: '/producer/$id',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerOrdersOrderIdRoute = BuyerOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => BuyerOrdersRoute,
} as any)
const BuyerOfferListingIdRoute = BuyerOfferListingIdRouteImport.update({
  id: '/offer/$listingId',
  path: '/offer/$listingId',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerNegotiationOfferIdRoute = BuyerNegotiationOfferIdRouteImport.update({
  id: '/negotiation/$offerId',
  path: '/negotiation/$offerId',
  getParentRoute: () => BuyerRoute,
} as any)
const FarmerOrdersOfferIdCounterRoute =
  FarmerOrdersOfferIdCounterRouteImport.update({
    id: '/$offerId/counter',
    path: '/$offerId/counter',
    getParentRoute: () => FarmerOrdersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buyer': typeof BuyerRouteWithChildren
  '/farmer': typeof FarmerRouteWithChildren
  '/login': typeof LoginRoute
  '/buyer/account': typeof BuyerAccountRoute
  '/buyer/discover': typeof BuyerDiscoverRoute
  '/buyer/messages': typeof BuyerMessagesRoute
  '/buyer/orders': typeof BuyerOrdersRouteWithChildren
  '/buyer/payment': typeof BuyerPaymentRoute
  '/buyer/reports': typeof BuyerReportsRoute
  '/buyer/subscriptions': typeof BuyerSubscriptionsRoute
  '/farmer/analytics': typeof FarmerAnalyticsRoute
  '/farmer/billing': typeof FarmerBillingRoute
  '/farmer/community': typeof FarmerCommunityRoute
  '/farmer/home': typeof FarmerHomeRoute
  '/farmer/journal': typeof FarmerJournalRouteWithChildren
  '/farmer/offers': typeof FarmerOffersRoute
  '/farmer/orders': typeof FarmerOrdersRouteWithChildren
  '/farmer/premium': typeof FarmerPremiumRoute
  '/farmer/prices': typeof FarmerPricesRoute
  '/farmer/settings': typeof FarmerSettingsRouteWithChildren
  '/farmer/storefront': typeof FarmerStorefrontRoute
  '/onboarding/buyer': typeof OnboardingBuyerRoute
  '/onboarding/farmer': typeof OnboardingFarmerRoute
  '/buyer/negotiation/$offerId': typeof BuyerNegotiationOfferIdRoute
  '/buyer/offer/$listingId': typeof BuyerOfferListingIdRoute
  '/buyer/orders/$orderId': typeof BuyerOrdersOrderIdRoute
  '/buyer/producer/$id': typeof BuyerProducerIdRoute
  '/buyer/subscription/$producerId': typeof BuyerSubscriptionProducerIdRoute
  '/farmer/journal/$entryId': typeof FarmerJournalEntryIdRoute
  '/farmer/journal/new': typeof FarmerJournalNewRoute
  '/farmer/settings/notifs': typeof FarmerSettingsNotifsRoute
  '/farmer/journal/': typeof FarmerJournalIndexRoute
  '/farmer/orders/$offerId/counter': typeof FarmerOrdersOfferIdCounterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buyer': typeof BuyerRouteWithChildren
  '/farmer': typeof FarmerRouteWithChildren
  '/login': typeof LoginRoute
  '/buyer/account': typeof BuyerAccountRoute
  '/buyer/discover': typeof BuyerDiscoverRoute
  '/buyer/messages': typeof BuyerMessagesRoute
  '/buyer/orders': typeof BuyerOrdersRouteWithChildren
  '/buyer/payment': typeof BuyerPaymentRoute
  '/buyer/reports': typeof BuyerReportsRoute
  '/buyer/subscriptions': typeof BuyerSubscriptionsRoute
  '/farmer/analytics': typeof FarmerAnalyticsRoute
  '/farmer/billing': typeof FarmerBillingRoute
  '/farmer/community': typeof FarmerCommunityRoute
  '/farmer/home': typeof FarmerHomeRoute
  '/farmer/offers': typeof FarmerOffersRoute
  '/farmer/orders': typeof FarmerOrdersRouteWithChildren
  '/farmer/premium': typeof FarmerPremiumRoute
  '/farmer/prices': typeof FarmerPricesRoute
  '/farmer/settings': typeof FarmerSettingsRouteWithChildren
  '/farmer/storefront': typeof FarmerStorefrontRoute
  '/onboarding/buyer': typeof OnboardingBuyerRoute
  '/onboarding/farmer': typeof OnboardingFarmerRoute
  '/buyer/negotiation/$offerId': typeof BuyerNegotiationOfferIdRoute
  '/buyer/offer/$listingId': typeof BuyerOfferListingIdRoute
  '/buyer/orders/$orderId': typeof BuyerOrdersOrderIdRoute
  '/buyer/producer/$id': typeof BuyerProducerIdRoute
  '/buyer/subscription/$producerId': typeof BuyerSubscriptionProducerIdRoute
  '/farmer/journal/$entryId': typeof FarmerJournalEntryIdRoute
  '/farmer/journal/new': typeof FarmerJournalNewRoute
  '/farmer/settings/notifs': typeof FarmerSettingsNotifsRoute
  '/farmer/journal': typeof FarmerJournalIndexRoute
  '/farmer/orders/$offerId/counter': typeof FarmerOrdersOfferIdCounterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buyer': typeof BuyerRouteWithChildren
  '/farmer': typeof FarmerRouteWithChildren
  '/login': typeof LoginRoute
  '/buyer/account': typeof BuyerAccountRoute
  '/buyer/discover': typeof BuyerDiscoverRoute
  '/buyer/messages': typeof BuyerMessagesRoute
  '/buyer/orders': typeof BuyerOrdersRouteWithChildren
  '/buyer/payment': typeof BuyerPaymentRoute
  '/buyer/reports': typeof BuyerReportsRoute
  '/buyer/subscriptions': typeof BuyerSubscriptionsRoute
  '/farmer/analytics': typeof FarmerAnalyticsRoute
  '/farmer/billing': typeof FarmerBillingRoute
  '/farmer/community': typeof FarmerCommunityRoute
  '/farmer/home': typeof FarmerHomeRoute
  '/farmer/journal': typeof FarmerJournalRouteWithChildren
  '/farmer/offers': typeof FarmerOffersRoute
  '/farmer/orders': typeof FarmerOrdersRouteWithChildren
  '/farmer/premium': typeof FarmerPremiumRoute
  '/farmer/prices': typeof FarmerPricesRoute
  '/farmer/settings': typeof FarmerSettingsRouteWithChildren
  '/farmer/storefront': typeof FarmerStorefrontRoute
  '/onboarding/buyer': typeof OnboardingBuyerRoute
  '/onboarding/farmer': typeof OnboardingFarmerRoute
  '/buyer/negotiation/$offerId': typeof BuyerNegotiationOfferIdRoute
  '/buyer/offer/$listingId': typeof BuyerOfferListingIdRoute
  '/buyer/orders/$orderId': typeof BuyerOrdersOrderIdRoute
  '/buyer/producer/$id': typeof BuyerProducerIdRoute
  '/buyer/subscription/$producerId': typeof BuyerSubscriptionProducerIdRoute
  '/farmer/journal/$entryId': typeof FarmerJournalEntryIdRoute
  '/farmer/journal/new': typeof FarmerJournalNewRoute
  '/farmer/settings/notifs': typeof FarmerSettingsNotifsRoute
  '/farmer/journal/': typeof FarmerJournalIndexRoute
  '/farmer/orders/$offerId/counter': typeof FarmerOrdersOfferIdCounterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buyer'
    | '/farmer'
    | '/login'
    | '/buyer/account'
    | '/buyer/discover'
    | '/buyer/messages'
    | '/buyer/orders'
    | '/buyer/payment'
    | '/buyer/reports'
    | '/buyer/subscriptions'
    | '/farmer/analytics'
    | '/farmer/billing'
    | '/farmer/community'
    | '/farmer/home'
    | '/farmer/journal'
    | '/farmer/offers'
    | '/farmer/orders'
    | '/farmer/premium'
    | '/farmer/prices'
    | '/farmer/settings'
    | '/farmer/storefront'
    | '/onboarding/buyer'
    | '/onboarding/farmer'
    | '/buyer/negotiation/$offerId'
    | '/buyer/offer/$listingId'
    | '/buyer/orders/$orderId'
    | '/buyer/producer/$id'
    | '/buyer/subscription/$producerId'
    | '/farmer/journal/$entryId'
    | '/farmer/journal/new'
    | '/farmer/settings/notifs'
    | '/farmer/journal/'
    | '/farmer/orders/$offerId/counter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buyer'
    | '/farmer'
    | '/login'
    | '/buyer/account'
    | '/buyer/discover'
    | '/buyer/messages'
    | '/buyer/orders'
    | '/buyer/payment'
    | '/buyer/reports'
    | '/buyer/subscriptions'
    | '/farmer/analytics'
    | '/farmer/billing'
    | '/farmer/community'
    | '/farmer/home'
    | '/farmer/offers'
    | '/farmer/orders'
    | '/farmer/premium'
    | '/farmer/prices'
    | '/farmer/settings'
    | '/farmer/storefront'
    | '/onboarding/buyer'
    | '/onboarding/farmer'
    | '/buyer/negotiation/$offerId'
    | '/buyer/offer/$listingId'
    | '/buyer/orders/$orderId'
    | '/buyer/producer/$id'
    | '/buyer/subscription/$producerId'
    | '/farmer/journal/$entryId'
    | '/farmer/journal/new'
    | '/farmer/settings/notifs'
    | '/farmer/journal'
    | '/farmer/orders/$offerId/counter'
  id:
    | '__root__'
    | '/'
    | '/buyer'
    | '/farmer'
    | '/login'
    | '/buyer/account'
    | '/buyer/discover'
    | '/buyer/messages'
    | '/buyer/orders'
    | '/buyer/payment'
    | '/buyer/reports'
    | '/buyer/subscriptions'
    | '/farmer/analytics'
    | '/farmer/billing'
    | '/farmer/community'
    | '/farmer/home'
    | '/farmer/journal'
    | '/farmer/offers'
    | '/farmer/orders'
    | '/farmer/premium'
    | '/farmer/prices'
    | '/farmer/settings'
    | '/farmer/storefront'
    | '/onboarding/buyer'
    | '/onboarding/farmer'
    | '/buyer/negotiation/$offerId'
    | '/buyer/offer/$listingId'
    | '/buyer/orders/$orderId'
    | '/buyer/producer/$id'
    | '/buyer/subscription/$producerId'
    | '/farmer/journal/$entryId'
    | '/farmer/journal/new'
    | '/farmer/settings/notifs'
    | '/farmer/journal/'
    | '/farmer/orders/$offerId/counter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuyerRoute: typeof BuyerRouteWithChildren
  FarmerRoute: typeof FarmerRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingBuyerRoute: typeof OnboardingBuyerRoute
  OnboardingFarmerRoute: typeof OnboardingFarmerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer': {
      id: '/farmer'
      path: '/farmer'
      fullPath: '/farmer'
      preLoaderRoute: typeof FarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer': {
      id: '/buyer'
      path: '/buyer'
      fullPath: '/buyer'
      preLoaderRoute: typeof BuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/farmer': {
      id: '/onboarding/farmer'
      path: '/onboarding/farmer'
      fullPath: '/onboarding/farmer'
      preLoaderRoute: typeof OnboardingFarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/buyer': {
      id: '/onboarding/buyer'
      path: '/onboarding/buyer'
      fullPath: '/onboarding/buyer'
      preLoaderRoute: typeof OnboardingBuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/storefront': {
      id: '/farmer/storefront'
      path: '/storefront'
      fullPath: '/farmer/storefront'
      preLoaderRoute: typeof FarmerStorefrontRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/settings': {
      id: '/farmer/settings'
      path: '/settings'
      fullPath: '/farmer/settings'
      preLoaderRoute: typeof FarmerSettingsRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/prices': {
      id: '/farmer/prices'
      path: '/prices'
      fullPath: '/farmer/prices'
      preLoaderRoute: typeof FarmerPricesRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/premium': {
      id: '/farmer/premium'
      path: '/premium'
      fullPath: '/farmer/premium'
      preLoaderRoute: typeof FarmerPremiumRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/orders': {
      id: '/farmer/orders'
      path: '/orders'
      fullPath: '/farmer/orders'
      preLoaderRoute: typeof FarmerOrdersRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/offers': {
      id: '/farmer/offers'
      path: '/offers'
      fullPath: '/farmer/offers'
      preLoaderRoute: typeof FarmerOffersRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/journal': {
      id: '/farmer/journal'
      path: '/journal'
      fullPath: '/farmer/journal'
      preLoaderRoute: typeof FarmerJournalRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/home': {
      id: '/farmer/home'
      path: '/home'
      fullPath: '/farmer/home'
      preLoaderRoute: typeof FarmerHomeRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/community': {
      id: '/farmer/community'
      path: '/community'
      fullPath: '/farmer/community'
      preLoaderRoute: typeof FarmerCommunityRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/billing': {
      id: '/farmer/billing'
      path: '/billing'
      fullPath: '/farmer/billing'
      preLoaderRoute: typeof FarmerBillingRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/analytics': {
      id: '/farmer/analytics'
      path: '/analytics'
      fullPath: '/farmer/analytics'
      preLoaderRoute: typeof FarmerAnalyticsRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/buyer/subscriptions': {
      id: '/buyer/subscriptions'
      path: '/subscriptions'
      fullPath: '/buyer/subscriptions'
      preLoaderRoute: typeof BuyerSubscriptionsRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/reports': {
      id: '/buyer/reports'
      path: '/reports'
      fullPath: '/buyer/reports'
      preLoaderRoute: typeof BuyerReportsRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/payment': {
      id: '/buyer/payment'
      path: '/payment'
      fullPath: '/buyer/payment'
      preLoaderRoute: typeof BuyerPaymentRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/orders': {
      id: '/buyer/orders'
      path: '/orders'
      fullPath: '/buyer/orders'
      preLoaderRoute: typeof BuyerOrdersRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/messages': {
      id: '/buyer/messages'
      path: '/messages'
      fullPath: '/buyer/messages'
      preLoaderRoute: typeof BuyerMessagesRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/discover': {
      id: '/buyer/discover'
      path: '/discover'
      fullPath: '/buyer/discover'
      preLoaderRoute: typeof BuyerDiscoverRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/account': {
      id: '/buyer/account'
      path: '/account'
      fullPath: '/buyer/account'
      preLoaderRoute: typeof BuyerAccountRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/farmer/journal/': {
      id: '/farmer/journal/'
      path: '/'
      fullPath: '/farmer/journal/'
      preLoaderRoute: typeof FarmerJournalIndexRouteImport
      parentRoute: typeof FarmerJournalRoute
    }
    '/farmer/settings/notifs': {
      id: '/farmer/settings/notifs'
      path: '/notifs'
      fullPath: '/farmer/settings/notifs'
      preLoaderRoute: typeof FarmerSettingsNotifsRouteImport
      parentRoute: typeof FarmerSettingsRoute
    }
    '/farmer/journal/new': {
      id: '/farmer/journal/new'
      path: '/new'
      fullPath: '/farmer/journal/new'
      preLoaderRoute: typeof FarmerJournalNewRouteImport
      parentRoute: typeof FarmerJournalRoute
    }
    '/farmer/journal/$entryId': {
      id: '/farmer/journal/$entryId'
      path: '/$entryId'
      fullPath: '/farmer/journal/$entryId'
      preLoaderRoute: typeof FarmerJournalEntryIdRouteImport
      parentRoute: typeof FarmerJournalRoute
    }
    '/buyer/subscription/$producerId': {
      id: '/buyer/subscription/$producerId'
      path: '/subscription/$producerId'
      fullPath: '/buyer/subscription/$producerId'
      preLoaderRoute: typeof BuyerSubscriptionProducerIdRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/producer/$id': {
      id: '/buyer/producer/$id'
      path: '/producer/$id'
      fullPath: '/buyer/producer/$id'
      preLoaderRoute: typeof BuyerProducerIdRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/orders/$orderId': {
      id: '/buyer/orders/$orderId'
      path: '/$orderId'
      fullPath: '/buyer/orders/$orderId'
      preLoaderRoute: typeof BuyerOrdersOrderIdRouteImport
      parentRoute: typeof BuyerOrdersRoute
    }
    '/buyer/offer/$listingId': {
      id: '/buyer/offer/$listingId'
      path: '/offer/$listingId'
      fullPath: '/buyer/offer/$listingId'
      preLoaderRoute: typeof BuyerOfferListingIdRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/negotiation/$offerId': {
      id: '/buyer/negotiation/$offerId'
      path: '/negotiation/$offerId'
      fullPath: '/buyer/negotiation/$offerId'
      preLoaderRoute: typeof BuyerNegotiationOfferIdRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/farmer/orders/$offerId/counter': {
      id: '/farmer/orders/$offerId/counter'
      path: '/$offerId/counter'
      fullPath: '/farmer/orders/$offerId/counter'
      preLoaderRoute: typeof FarmerOrdersOfferIdCounterRouteImport
      parentRoute: typeof FarmerOrdersRoute
    }
  }
}

interface BuyerOrdersRouteChildren {
  BuyerOrdersOrderIdRoute: typeof BuyerOrdersOrderIdRoute
}

const BuyerOrdersRouteChildren: BuyerOrdersRouteChildren = {
  BuyerOrdersOrderIdRoute: BuyerOrdersOrderIdRoute,
}

const BuyerOrdersRouteWithChildren = BuyerOrdersRoute._addFileChildren(
  BuyerOrdersRouteChildren,
)

interface BuyerRouteChildren {
  BuyerAccountRoute: typeof BuyerAccountRoute
  BuyerDiscoverRoute: typeof BuyerDiscoverRoute
  BuyerMessagesRoute: typeof BuyerMessagesRoute
  BuyerOrdersRoute: typeof BuyerOrdersRouteWithChildren
  BuyerPaymentRoute: typeof BuyerPaymentRoute
  BuyerReportsRoute: typeof BuyerReportsRoute
  BuyerSubscriptionsRoute: typeof BuyerSubscriptionsRoute
  BuyerNegotiationOfferIdRoute: typeof BuyerNegotiationOfferIdRoute
  BuyerOfferListingIdRoute: typeof BuyerOfferListingIdRoute
  BuyerProducerIdRoute: typeof BuyerProducerIdRoute
  BuyerSubscriptionProducerIdRoute: typeof BuyerSubscriptionProducerIdRoute
}

const BuyerRouteChildren: BuyerRouteChildren = {
  BuyerAccountRoute: BuyerAccountRoute,
  BuyerDiscoverRoute: BuyerDiscoverRoute,
  BuyerMessagesRoute: BuyerMessagesRoute,
  BuyerOrdersRoute: BuyerOrdersRouteWithChildren,
  BuyerPaymentRoute: BuyerPaymentRoute,
  BuyerReportsRoute: BuyerReportsRoute,
  BuyerSubscriptionsRoute: BuyerSubscriptionsRoute,
  BuyerNegotiationOfferIdRoute: BuyerNegotiationOfferIdRoute,
  BuyerOfferListingIdRoute: BuyerOfferListingIdRoute,
  BuyerProducerIdRoute: BuyerProducerIdRoute,
  BuyerSubscriptionProducerIdRoute: BuyerSubscriptionProducerIdRoute,
}

const BuyerRouteWithChildren = BuyerRoute._addFileChildren(BuyerRouteChildren)

interface FarmerJournalRouteChildren {
  FarmerJournalEntryIdRoute: typeof FarmerJournalEntryIdRoute
  FarmerJournalNewRoute: typeof FarmerJournalNewRoute
  FarmerJournalIndexRoute: typeof FarmerJournalIndexRoute
}

const FarmerJournalRouteChildren: FarmerJournalRouteChildren = {
  FarmerJournalEntryIdRoute: FarmerJournalEntryIdRoute,
  FarmerJournalNewRoute: FarmerJournalNewRoute,
  FarmerJournalIndexRoute: FarmerJournalIndexRoute,
}

const FarmerJournalRouteWithChildren = FarmerJournalRoute._addFileChildren(
  FarmerJournalRouteChildren,
)

interface FarmerOrdersRouteChildren {
  FarmerOrdersOfferIdCounterRoute: typeof FarmerOrdersOfferIdCounterRoute
}

const FarmerOrdersRouteChildren: FarmerOrdersRouteChildren = {
  FarmerOrdersOfferIdCounterRoute: FarmerOrdersOfferIdCounterRoute,
}

const FarmerOrdersRouteWithChildren = FarmerOrdersRoute._addFileChildren(
  FarmerOrdersRouteChildren,
)

interface FarmerSettingsRouteChildren {
  FarmerSettingsNotifsRoute: typeof FarmerSettingsNotifsRoute
}

const FarmerSettingsRouteChildren: FarmerSettingsRouteChildren = {
  FarmerSettingsNotifsRoute: FarmerSettingsNotifsRoute,
}

const FarmerSettingsRouteWithChildren = FarmerSettingsRoute._addFileChildren(
  FarmerSettingsRouteChildren,
)

interface FarmerRouteChildren {
  FarmerAnalyticsRoute: typeof FarmerAnalyticsRoute
  FarmerBillingRoute: typeof FarmerBillingRoute
  FarmerCommunityRoute: typeof FarmerCommunityRoute
  FarmerHomeRoute: typeof FarmerHomeRoute
  FarmerJournalRoute: typeof FarmerJournalRouteWithChildren
  FarmerOffersRoute: typeof FarmerOffersRoute
  FarmerOrdersRoute: typeof FarmerOrdersRouteWithChildren
  FarmerPremiumRoute: typeof FarmerPremiumRoute
  FarmerPricesRoute: typeof FarmerPricesRoute
  FarmerSettingsRoute: typeof FarmerSettingsRouteWithChildren
  FarmerStorefrontRoute: typeof FarmerStorefrontRoute
}

const FarmerRouteChildren: FarmerRouteChildren = {
  FarmerAnalyticsRoute: FarmerAnalyticsRoute,
  FarmerBillingRoute: FarmerBillingRoute,
  FarmerCommunityRoute: FarmerCommunityRoute,
  FarmerHomeRoute: FarmerHomeRoute,
  FarmerJournalRoute: FarmerJournalRouteWithChildren,
  FarmerOffersRoute: FarmerOffersRoute,
  FarmerOrdersRoute: FarmerOrdersRouteWithChildren,
  FarmerPremiumRoute: FarmerPremiumRoute,
  FarmerPricesRoute: FarmerPricesRoute,
  FarmerSettingsRoute: FarmerSettingsRouteWithChildren,
  FarmerStorefrontRoute: FarmerStorefrontRoute,
}

const FarmerRouteWithChildren =
  FarmerRoute._addFileChildren(FarmerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuyerRoute: BuyerRouteWithChildren,
  FarmerRoute: FarmerRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingBuyerRoute: OnboardingBuyerRoute,
  OnboardingFarmerRoute: OnboardingFarmerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
