/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as FarmerRouteImport } from './routes/farmer'
import { Route as BuyerRouteImport } from './routes/buyer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as OnboardingFarmerRouteImport } from './routes/onboarding.farmer'
import { Route as OnboardingBuyerRouteImport } from './routes/onboarding.buyer'
import { Route as FarmerStorefrontRouteImport } from './routes/farmer.storefront'
import { Route as FarmerSettingsRouteImport } from './routes/farmer.settings'
import { Route as FarmerReferralRouteImport } from './routes/farmer.referral'
import { Route as FarmerPremiumRouteImport } from './routes/farmer.premium'
import { Route as FarmerJournalRouteImport } from './routes/farmer.journal'
import { Route as FarmerHomeRouteImport } from './routes/farmer.home'
import { Route as FarmerCommunityRouteImport } from './routes/farmer.community'
import { Route as FarmerBillingRouteImport } from './routes/farmer.billing'
import { Route as FarmerAnalyticsRouteImport } from './routes/farmer.analytics'
import { Route as BuyerSubscriptionsRouteImport } from './routes/buyer.subscriptions'
import { Route as BuyerRequestsRouteImport } from './routes/buyer.requests'
import { Route as BuyerReportsRouteImport } from './routes/buyer.reports'
import { Route as BuyerPaymentRouteImport } from './routes/buyer.payment'
import { Route as BuyerOrdersRouteImport } from './routes/buyer.orders'
import { Route as BuyerMessagesRouteImport } from './routes/buyer.messages'
import { Route as BuyerDiscoverRouteImport } from './routes/buyer.discover'
import { Route as BuyerCommunityRouteImport } from './routes/buyer.community'
import { Route as BuyerAccountRouteImport } from './routes/buyer.account'
import { Route as BatchListingIdRouteImport } from './routes/batch.$listingId'
import { Route as AdminKpiRouteImport } from './routes/admin.kpi'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as FarmerPricesIndexRouteImport } from './routes/farmer.prices.index'
import { Route as FarmerOrdersIndexRouteImport } from './routes/farmer.orders.index'
import { Route as FarmerJournalIndexRouteImport } from './routes/farmer.journal.index'
import { Route as BuyerPricesIndexRouteImport } from './routes/buyer.prices.index'
import { Route as FarmerSettingsNotifsRouteImport } from './routes/farmer.settings.notifs'
import { Route as FarmerPricesCropRouteImport } from './routes/farmer.prices.$crop'
import { Route as FarmerJournalNewRouteImport } from './routes/farmer.journal.new'
import { Route as FarmerJournalEntryIdRouteImport } from './routes/farmer.journal.$entryId'
import { Route as BuyerSubscriptionProducerIdRouteImport } from './routes/buyer.subscription.$producerId'
import { Route as BuyerSettingsNotifsRouteImport } from './routes/buyer.settings.notifs'
import { Route as BuyerProducerIdRouteImport } from './routes/buyer.producer.$id'
import { Route as BuyerPricesCropRouteImport } from './routes/buyer.prices.$crop'
import { Route as BuyerPayOfferIdRouteImport } from './routes/buyer.pay.$offerId'
import { Route as BuyerOrdersOrderIdRouteImport } from './routes/buyer.orders.$orderId'
import { Route as BuyerOfferListingIdRouteImport } from './routes/buyer.offer.$listingId'
import { Route as BuyerNegotiationOfferIdRouteImport } from './routes/buyer.negotiation.$offerId'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerRoute = FarmerRouteImport.update({
  id: '/farmer',
  path: '/farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerRoute = BuyerRouteImport.update({
  id: '/buyer',
  path: '/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingFarmerRoute = OnboardingFarmerRouteImport.update({
  id: '/onboarding/farmer',
  path: '/onboarding/farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingBuyerRoute = OnboardingBuyerRouteImport.update({
  id: '/onboarding/buyer',
  path: '/onboarding/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerStorefrontRoute = FarmerStorefrontRouteImport.update({
  id: '/storefront',
  path: '/storefront',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerSettingsRoute = FarmerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerReferralRoute = FarmerReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerPremiumRoute = FarmerPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerJournalRoute = FarmerJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerHomeRoute = FarmerHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerCommunityRoute = FarmerCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerBillingRoute = FarmerBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerAnalyticsRoute = FarmerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => FarmerRoute,
} as any)
const BuyerSubscriptionsRoute = BuyerSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerRequestsRoute = BuyerRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerReportsRoute = BuyerReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerPaymentRoute = BuyerPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerOrdersRoute = BuyerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerMessagesRoute = BuyerMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerDiscoverRoute = BuyerDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerCommunityRoute = BuyerCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerAccountRoute = BuyerAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => BuyerRoute,
} as any)
const BatchListingIdRoute = BatchListingIdRouteImport.update({
  id: '/batch/$listingId',
  path: '/batch/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKpiRoute = AdminKpiRouteImport.update({
  id: '/admin/kpi',
  path: '/admin/kpi',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const FarmerPricesIndexRoute = FarmerPricesIndexRouteImport.update({
  id: '/prices/',
  path: '/prices/',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerOrdersIndexRoute = FarmerOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerJournalIndexRoute = FarmerJournalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FarmerJournalRoute,
} as any)
const BuyerPricesIndexRoute = BuyerPricesIndexRouteImport.update({
  id: '/prices/',
  path: '/prices/',
  getParentRoute: () => BuyerRoute,
} as any)
const FarmerSettingsNotifsRoute = FarmerSettingsNotifsRouteImport.update({
  id: '/notifs',
  path: '/notifs',
  getParentRoute: () => FarmerSettingsRoute,
} as any)
const FarmerPricesCropRoute = FarmerPricesCropRouteImport.update({
  id: '/prices/$crop',
  path: '/prices/$crop',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerJournalNewRoute = FarmerJournalNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => FarmerJournalRoute,
} as any)
const FarmerJournalEntryIdRoute = FarmerJournalEntryIdRouteImport.update({
  id: '/$entryId',
  path: '/$entryId',
  getParentRoute: () => FarmerJournalRoute,
} as any)
const BuyerSubscriptionProducerIdRoute =
  BuyerSubscriptionProducerIdRouteImport.update({
    id: '/subscription/$producerId',
    path: '/subscription/$producerId',
    getParentRoute: () => BuyerRoute,
  } as any)
const BuyerSettingsNotifsRoute = BuyerSettingsNotifsRouteImport.update({
  id: '/settings/notifs',
  path: '/settings/notifs',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerProducerIdRoute = BuyerProducerIdRouteImport.update({
  id: '/producer/$id',
  path: '/producer/$id',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerPricesCropRoute = BuyerPricesCropRouteImport.update({
  id: '/prices/$crop',
  path: '/prices/$crop',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerPayOfferIdRoute = BuyerPayOfferIdRouteImport.update({
  id: '/pay/$offerId',
  path: '/pay/$offerId',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerOrdersOrderIdRoute = BuyerOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => BuyerOrdersRoute,
} as any)
const BuyerOfferListingIdRoute = BuyerOfferListingIdRouteImport.update({
  id: '/offer/$listingId',
  path: '/offer/$listingId',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerNegotiationOfferIdRoute = BuyerNegotiationOfferIdRouteImport.update({
  id: '/negotiation/$offerId',
  path: '/negotiation/$offerId',
  getParentRoute: () => BuyerRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buyer': typeof BuyerRouteWithChildren
  '/farmer': typeof FarmerRouteWithChildren
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/kpi': typeof AdminKpiRoute
  '/batch/$listingId': typeof BatchListingIdRoute
  '/buyer/account': typeof BuyerAccountRoute
  '/buyer/community': typeof BuyerCommunityRoute
  '/buyer/discover': typeof BuyerDiscoverRoute
  '/buyer/messages': typeof BuyerMessagesRoute
  '/buyer/orders': typeof BuyerOrdersRouteWithChildren
  '/buyer/payment': typeof BuyerPaymentRoute
  '/buyer/reports': typeof BuyerReportsRoute
  '/buyer/requests': typeof BuyerRequestsRoute
  '/buyer/subscriptions': typeof BuyerSubscriptionsRoute
  '/farmer/analytics': typeof FarmerAnalyticsRoute
  '/farmer/billing': typeof FarmerBillingRoute
  '/farmer/community': typeof FarmerCommunityRoute
  '/farmer/home': typeof FarmerHomeRoute
  '/farmer/journal': typeof FarmerJournalRouteWithChildren
  '/farmer/premium': typeof FarmerPremiumRoute
  '/farmer/referral': typeof FarmerReferralRoute
  '/farmer/settings': typeof FarmerSettingsRouteWithChildren
  '/farmer/storefront': typeof FarmerStorefrontRoute
  '/onboarding/buyer': typeof OnboardingBuyerRoute
  '/onboarding/farmer': typeof OnboardingFarmerRoute
  '/s/$slug': typeof SSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/buyer/negotiation/$offerId': typeof BuyerNegotiationOfferIdRoute
  '/buyer/offer/$listingId': typeof BuyerOfferListingIdRoute
  '/buyer/orders/$orderId': typeof BuyerOrdersOrderIdRoute
  '/buyer/pay/$offerId': typeof BuyerPayOfferIdRoute
  '/buyer/prices/$crop': typeof BuyerPricesCropRoute
  '/buyer/producer/$id': typeof BuyerProducerIdRoute
  '/buyer/settings/notifs': typeof BuyerSettingsNotifsRoute
  '/buyer/subscription/$producerId': typeof BuyerSubscriptionProducerIdRoute
  '/farmer/journal/$entryId': typeof FarmerJournalEntryIdRoute
  '/farmer/journal/new': typeof FarmerJournalNewRoute
  '/farmer/prices/$crop': typeof FarmerPricesCropRoute
  '/farmer/settings/notifs': typeof FarmerSettingsNotifsRoute
  '/buyer/prices/': typeof BuyerPricesIndexRoute
  '/farmer/journal/': typeof FarmerJournalIndexRoute
  '/farmer/orders/': typeof FarmerOrdersIndexRoute
  '/farmer/prices/': typeof FarmerPricesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buyer': typeof BuyerRouteWithChildren
  '/farmer': typeof FarmerRouteWithChildren
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/kpi': typeof AdminKpiRoute
  '/batch/$listingId': typeof BatchListingIdRoute
  '/buyer/account': typeof BuyerAccountRoute
  '/buyer/community': typeof BuyerCommunityRoute
  '/buyer/discover': typeof BuyerDiscoverRoute
  '/buyer/messages': typeof BuyerMessagesRoute
  '/buyer/orders': typeof BuyerOrdersRouteWithChildren
  '/buyer/payment': typeof BuyerPaymentRoute
  '/buyer/reports': typeof BuyerReportsRoute
  '/buyer/requests': typeof BuyerRequestsRoute
  '/buyer/subscriptions': typeof BuyerSubscriptionsRoute
  '/farmer/analytics': typeof FarmerAnalyticsRoute
  '/farmer/billing': typeof FarmerBillingRoute
  '/farmer/community': typeof FarmerCommunityRoute
  '/farmer/home': typeof FarmerHomeRoute
  '/farmer/premium': typeof FarmerPremiumRoute
  '/farmer/referral': typeof FarmerReferralRoute
  '/farmer/settings': typeof FarmerSettingsRouteWithChildren
  '/farmer/storefront': typeof FarmerStorefrontRoute
  '/onboarding/buyer': typeof OnboardingBuyerRoute
  '/onboarding/farmer': typeof OnboardingFarmerRoute
  '/s/$slug': typeof SSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/buyer/negotiation/$offerId': typeof BuyerNegotiationOfferIdRoute
  '/buyer/offer/$listingId': typeof BuyerOfferListingIdRoute
  '/buyer/orders/$orderId': typeof BuyerOrdersOrderIdRoute
  '/buyer/pay/$offerId': typeof BuyerPayOfferIdRoute
  '/buyer/prices/$crop': typeof BuyerPricesCropRoute
  '/buyer/producer/$id': typeof BuyerProducerIdRoute
  '/buyer/settings/notifs': typeof BuyerSettingsNotifsRoute
  '/buyer/subscription/$producerId': typeof BuyerSubscriptionProducerIdRoute
  '/farmer/journal/$entryId': typeof FarmerJournalEntryIdRoute
  '/farmer/journal/new': typeof FarmerJournalNewRoute
  '/farmer/prices/$crop': typeof FarmerPricesCropRoute
  '/farmer/settings/notifs': typeof FarmerSettingsNotifsRoute
  '/buyer/prices': typeof BuyerPricesIndexRoute
  '/farmer/journal': typeof FarmerJournalIndexRoute
  '/farmer/orders': typeof FarmerOrdersIndexRoute
  '/farmer/prices': typeof FarmerPricesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buyer': typeof BuyerRouteWithChildren
  '/farmer': typeof FarmerRouteWithChildren
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/kpi': typeof AdminKpiRoute
  '/batch/$listingId': typeof BatchListingIdRoute
  '/buyer/account': typeof BuyerAccountRoute
  '/buyer/community': typeof BuyerCommunityRoute
  '/buyer/discover': typeof BuyerDiscoverRoute
  '/buyer/messages': typeof BuyerMessagesRoute
  '/buyer/orders': typeof BuyerOrdersRouteWithChildren
  '/buyer/payment': typeof BuyerPaymentRoute
  '/buyer/reports': typeof BuyerReportsRoute
  '/buyer/requests': typeof BuyerRequestsRoute
  '/buyer/subscriptions': typeof BuyerSubscriptionsRoute
  '/farmer/analytics': typeof FarmerAnalyticsRoute
  '/farmer/billing': typeof FarmerBillingRoute
  '/farmer/community': typeof FarmerCommunityRoute
  '/farmer/home': typeof FarmerHomeRoute
  '/farmer/journal': typeof FarmerJournalRouteWithChildren
  '/farmer/premium': typeof FarmerPremiumRoute
  '/farmer/referral': typeof FarmerReferralRoute
  '/farmer/settings': typeof FarmerSettingsRouteWithChildren
  '/farmer/storefront': typeof FarmerStorefrontRoute
  '/onboarding/buyer': typeof OnboardingBuyerRoute
  '/onboarding/farmer': typeof OnboardingFarmerRoute
  '/s/$slug': typeof SSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/buyer/negotiation/$offerId': typeof BuyerNegotiationOfferIdRoute
  '/buyer/offer/$listingId': typeof BuyerOfferListingIdRoute
  '/buyer/orders/$orderId': typeof BuyerOrdersOrderIdRoute
  '/buyer/pay/$offerId': typeof BuyerPayOfferIdRoute
  '/buyer/prices/$crop': typeof BuyerPricesCropRoute
  '/buyer/producer/$id': typeof BuyerProducerIdRoute
  '/buyer/settings/notifs': typeof BuyerSettingsNotifsRoute
  '/buyer/subscription/$producerId': typeof BuyerSubscriptionProducerIdRoute
  '/farmer/journal/$entryId': typeof FarmerJournalEntryIdRoute
  '/farmer/journal/new': typeof FarmerJournalNewRoute
  '/farmer/prices/$crop': typeof FarmerPricesCropRoute
  '/farmer/settings/notifs': typeof FarmerSettingsNotifsRoute
  '/buyer/prices/': typeof BuyerPricesIndexRoute
  '/farmer/journal/': typeof FarmerJournalIndexRoute
  '/farmer/orders/': typeof FarmerOrdersIndexRoute
  '/farmer/prices/': typeof FarmerPricesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buyer'
    | '/farmer'
    | '/join'
    | '/login'
    | '/mcp'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/kpi'
    | '/batch/$listingId'
    | '/buyer/account'
    | '/buyer/community'
    | '/buyer/discover'
    | '/buyer/messages'
    | '/buyer/orders'
    | '/buyer/payment'
    | '/buyer/reports'
    | '/buyer/requests'
    | '/buyer/subscriptions'
    | '/farmer/analytics'
    | '/farmer/billing'
    | '/farmer/community'
    | '/farmer/home'
    | '/farmer/journal'
    | '/farmer/premium'
    | '/farmer/referral'
    | '/farmer/settings'
    | '/farmer/storefront'
    | '/onboarding/buyer'
    | '/onboarding/farmer'
    | '/s/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/buyer/negotiation/$offerId'
    | '/buyer/offer/$listingId'
    | '/buyer/orders/$orderId'
    | '/buyer/pay/$offerId'
    | '/buyer/prices/$crop'
    | '/buyer/producer/$id'
    | '/buyer/settings/notifs'
    | '/buyer/subscription/$producerId'
    | '/farmer/journal/$entryId'
    | '/farmer/journal/new'
    | '/farmer/prices/$crop'
    | '/farmer/settings/notifs'
    | '/buyer/prices/'
    | '/farmer/journal/'
    | '/farmer/orders/'
    | '/farmer/prices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buyer'
    | '/farmer'
    | '/join'
    | '/login'
    | '/mcp'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/kpi'
    | '/batch/$listingId'
    | '/buyer/account'
    | '/buyer/community'
    | '/buyer/discover'
    | '/buyer/messages'
    | '/buyer/orders'
    | '/buyer/payment'
    | '/buyer/reports'
    | '/buyer/requests'
    | '/buyer/subscriptions'
    | '/farmer/analytics'
    | '/farmer/billing'
    | '/farmer/community'
    | '/farmer/home'
    | '/farmer/premium'
    | '/farmer/referral'
    | '/farmer/settings'
    | '/farmer/storefront'
    | '/onboarding/buyer'
    | '/onboarding/farmer'
    | '/s/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/buyer/negotiation/$offerId'
    | '/buyer/offer/$listingId'
    | '/buyer/orders/$orderId'
    | '/buyer/pay/$offerId'
    | '/buyer/prices/$crop'
    | '/buyer/producer/$id'
    | '/buyer/settings/notifs'
    | '/buyer/subscription/$producerId'
    | '/farmer/journal/$entryId'
    | '/farmer/journal/new'
    | '/farmer/prices/$crop'
    | '/farmer/settings/notifs'
    | '/buyer/prices'
    | '/farmer/journal'
    | '/farmer/orders'
    | '/farmer/prices'
  id:
    | '__root__'
    | '/'
    | '/buyer'
    | '/farmer'
    | '/join'
    | '/login'
    | '/mcp'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/kpi'
    | '/batch/$listingId'
    | '/buyer/account'
    | '/buyer/community'
    | '/buyer/discover'
    | '/buyer/messages'
    | '/buyer/orders'
    | '/buyer/payment'
    | '/buyer/reports'
    | '/buyer/requests'
    | '/buyer/subscriptions'
    | '/farmer/analytics'
    | '/farmer/billing'
    | '/farmer/community'
    | '/farmer/home'
    | '/farmer/journal'
    | '/farmer/premium'
    | '/farmer/referral'
    | '/farmer/settings'
    | '/farmer/storefront'
    | '/onboarding/buyer'
    | '/onboarding/farmer'
    | '/s/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/buyer/negotiation/$offerId'
    | '/buyer/offer/$listingId'
    | '/buyer/orders/$orderId'
    | '/buyer/pay/$offerId'
    | '/buyer/prices/$crop'
    | '/buyer/producer/$id'
    | '/buyer/settings/notifs'
    | '/buyer/subscription/$producerId'
    | '/farmer/journal/$entryId'
    | '/farmer/journal/new'
    | '/farmer/prices/$crop'
    | '/farmer/settings/notifs'
    | '/buyer/prices/'
    | '/farmer/journal/'
    | '/farmer/orders/'
    | '/farmer/prices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuyerRoute: typeof BuyerRouteWithChildren
  FarmerRoute: typeof FarmerRouteWithChildren
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AdminKpiRoute: typeof AdminKpiRoute
  BatchListingIdRoute: typeof BatchListingIdRoute
  OnboardingBuyerRoute: typeof OnboardingBuyerRoute
  OnboardingFarmerRoute: typeof OnboardingFarmerRoute
  SSlugRoute: typeof SSlugRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer': {
      id: '/farmer'
      path: '/farmer'
      fullPath: '/farmer'
      preLoaderRoute: typeof FarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer': {
      id: '/buyer'
      path: '/buyer'
      fullPath: '/buyer'
      preLoaderRoute: typeof BuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/farmer': {
      id: '/onboarding/farmer'
      path: '/onboarding/farmer'
      fullPath: '/onboarding/farmer'
      preLoaderRoute: typeof OnboardingFarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/buyer': {
      id: '/onboarding/buyer'
      path: '/onboarding/buyer'
      fullPath: '/onboarding/buyer'
      preLoaderRoute: typeof OnboardingBuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/storefront': {
      id: '/farmer/storefront'
      path: '/storefront'
      fullPath: '/farmer/storefront'
      preLoaderRoute: typeof FarmerStorefrontRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/settings': {
      id: '/farmer/settings'
      path: '/settings'
      fullPath: '/farmer/settings'
      preLoaderRoute: typeof FarmerSettingsRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/referral': {
      id: '/farmer/referral'
      path: '/referral'
      fullPath: '/farmer/referral'
      preLoaderRoute: typeof FarmerReferralRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/premium': {
      id: '/farmer/premium'
      path: '/premium'
      fullPath: '/farmer/premium'
      preLoaderRoute: typeof FarmerPremiumRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/journal': {
      id: '/farmer/journal'
      path: '/journal'
      fullPath: '/farmer/journal'
      preLoaderRoute: typeof FarmerJournalRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/home': {
      id: '/farmer/home'
      path: '/home'
      fullPath: '/farmer/home'
      preLoaderRoute: typeof FarmerHomeRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/community': {
      id: '/farmer/community'
      path: '/community'
      fullPath: '/farmer/community'
      preLoaderRoute: typeof FarmerCommunityRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/billing': {
      id: '/farmer/billing'
      path: '/billing'
      fullPath: '/farmer/billing'
      preLoaderRoute: typeof FarmerBillingRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/analytics': {
      id: '/farmer/analytics'
      path: '/analytics'
      fullPath: '/farmer/analytics'
      preLoaderRoute: typeof FarmerAnalyticsRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/buyer/subscriptions': {
      id: '/buyer/subscriptions'
      path: '/subscriptions'
      fullPath: '/buyer/subscriptions'
      preLoaderRoute: typeof BuyerSubscriptionsRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/requests': {
      id: '/buyer/requests'
      path: '/requests'
      fullPath: '/buyer/requests'
      preLoaderRoute: typeof BuyerRequestsRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/reports': {
      id: '/buyer/reports'
      path: '/reports'
      fullPath: '/buyer/reports'
      preLoaderRoute: typeof BuyerReportsRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/payment': {
      id: '/buyer/payment'
      path: '/payment'
      fullPath: '/buyer/payment'
      preLoaderRoute: typeof BuyerPaymentRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/orders': {
      id: '/buyer/orders'
      path: '/orders'
      fullPath: '/buyer/orders'
      preLoaderRoute: typeof BuyerOrdersRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/messages': {
      id: '/buyer/messages'
      path: '/messages'
      fullPath: '/buyer/messages'
      preLoaderRoute: typeof BuyerMessagesRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/discover': {
      id: '/buyer/discover'
      path: '/discover'
      fullPath: '/buyer/discover'
      preLoaderRoute: typeof BuyerDiscoverRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/community': {
      id: '/buyer/community'
      path: '/community'
      fullPath: '/buyer/community'
      preLoaderRoute: typeof BuyerCommunityRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/account': {
      id: '/buyer/account'
      path: '/account'
      fullPath: '/buyer/account'
      preLoaderRoute: typeof BuyerAccountRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/batch/$listingId': {
      id: '/batch/$listingId'
      path: '/batch/$listingId'
      fullPath: '/batch/$listingId'
      preLoaderRoute: typeof BatchListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kpi': {
      id: '/admin/kpi'
      path: '/admin/kpi'
      fullPath: '/admin/kpi'
      preLoaderRoute: typeof AdminKpiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/prices/': {
      id: '/farmer/prices/'
      path: '/prices'
      fullPath: '/farmer/prices/'
      preLoaderRoute: typeof FarmerPricesIndexRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/orders/': {
      id: '/farmer/orders/'
      path: '/orders'
      fullPath: '/farmer/orders/'
      preLoaderRoute: typeof FarmerOrdersIndexRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/journal/': {
      id: '/farmer/journal/'
      path: '/'
      fullPath: '/farmer/journal/'
      preLoaderRoute: typeof FarmerJournalIndexRouteImport
      parentRoute: typeof FarmerJournalRoute
    }
    '/buyer/prices/': {
      id: '/buyer/prices/'
      path: '/prices'
      fullPath: '/buyer/prices/'
      preLoaderRoute: typeof BuyerPricesIndexRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/farmer/settings/notifs': {
      id: '/farmer/settings/notifs'
      path: '/notifs'
      fullPath: '/farmer/settings/notifs'
      preLoaderRoute: typeof FarmerSettingsNotifsRouteImport
      parentRoute: typeof FarmerSettingsRoute
    }
    '/farmer/prices/$crop': {
      id: '/farmer/prices/$crop'
      path: '/prices/$crop'
      fullPath: '/farmer/prices/$crop'
      preLoaderRoute: typeof FarmerPricesCropRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/journal/new': {
      id: '/farmer/journal/new'
      path: '/new'
      fullPath: '/farmer/journal/new'
      preLoaderRoute: typeof FarmerJournalNewRouteImport
      parentRoute: typeof FarmerJournalRoute
    }
    '/farmer/journal/$entryId': {
      id: '/farmer/journal/$entryId'
      path: '/$entryId'
      fullPath: '/farmer/journal/$entryId'
      preLoaderRoute: typeof FarmerJournalEntryIdRouteImport
      parentRoute: typeof FarmerJournalRoute
    }
    '/buyer/subscription/$producerId': {
      id: '/buyer/subscription/$producerId'
      path: '/subscription/$producerId'
      fullPath: '/buyer/subscription/$producerId'
      preLoaderRoute: typeof BuyerSubscriptionProducerIdRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/settings/notifs': {
      id: '/buyer/settings/notifs'
      path: '/settings/notifs'
      fullPath: '/buyer/settings/notifs'
      preLoaderRoute: typeof BuyerSettingsNotifsRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/producer/$id': {
      id: '/buyer/producer/$id'
      path: '/producer/$id'
      fullPath: '/buyer/producer/$id'
      preLoaderRoute: typeof BuyerProducerIdRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/prices/$crop': {
      id: '/buyer/prices/$crop'
      path: '/prices/$crop'
      fullPath: '/buyer/prices/$crop'
      preLoaderRoute: typeof BuyerPricesCropRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/pay/$offerId': {
      id: '/buyer/pay/$offerId'
      path: '/pay/$offerId'
      fullPath: '/buyer/pay/$offerId'
      preLoaderRoute: typeof BuyerPayOfferIdRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/orders/$orderId': {
      id: '/buyer/orders/$orderId'
      path: '/$orderId'
      fullPath: '/buyer/orders/$orderId'
      preLoaderRoute: typeof BuyerOrdersOrderIdRouteImport
      parentRoute: typeof BuyerOrdersRoute
    }
    '/buyer/offer/$listingId': {
      id: '/buyer/offer/$listingId'
      path: '/offer/$listingId'
      fullPath: '/buyer/offer/$listingId'
      preLoaderRoute: typeof BuyerOfferListingIdRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/negotiation/$offerId': {
      id: '/buyer/negotiation/$offerId'
      path: '/negotiation/$offerId'
      fullPath: '/buyer/negotiation/$offerId'
      preLoaderRoute: typeof BuyerNegotiationOfferIdRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BuyerOrdersRouteChildren {
  BuyerOrdersOrderIdRoute: typeof BuyerOrdersOrderIdRoute
}

const BuyerOrdersRouteChildren: BuyerOrdersRouteChildren = {
  BuyerOrdersOrderIdRoute: BuyerOrdersOrderIdRoute,
}

const BuyerOrdersRouteWithChildren = BuyerOrdersRoute._addFileChildren(
  BuyerOrdersRouteChildren,
)

interface BuyerRouteChildren {
  BuyerAccountRoute: typeof BuyerAccountRoute
  BuyerCommunityRoute: typeof BuyerCommunityRoute
  BuyerDiscoverRoute: typeof BuyerDiscoverRoute
  BuyerMessagesRoute: typeof BuyerMessagesRoute
  BuyerOrdersRoute: typeof BuyerOrdersRouteWithChildren
  BuyerPaymentRoute: typeof BuyerPaymentRoute
  BuyerReportsRoute: typeof BuyerReportsRoute
  BuyerRequestsRoute: typeof BuyerRequestsRoute
  BuyerSubscriptionsRoute: typeof BuyerSubscriptionsRoute
  BuyerNegotiationOfferIdRoute: typeof BuyerNegotiationOfferIdRoute
  BuyerOfferListingIdRoute: typeof BuyerOfferListingIdRoute
  BuyerPayOfferIdRoute: typeof BuyerPayOfferIdRoute
  BuyerPricesCropRoute: typeof BuyerPricesCropRoute
  BuyerProducerIdRoute: typeof BuyerProducerIdRoute
  BuyerSettingsNotifsRoute: typeof BuyerSettingsNotifsRoute
  BuyerSubscriptionProducerIdRoute: typeof BuyerSubscriptionProducerIdRoute
  BuyerPricesIndexRoute: typeof BuyerPricesIndexRoute
}

const BuyerRouteChildren: BuyerRouteChildren = {
  BuyerAccountRoute: BuyerAccountRoute,
  BuyerCommunityRoute: BuyerCommunityRoute,
  BuyerDiscoverRoute: BuyerDiscoverRoute,
  BuyerMessagesRoute: BuyerMessagesRoute,
  BuyerOrdersRoute: BuyerOrdersRouteWithChildren,
  BuyerPaymentRoute: BuyerPaymentRoute,
  BuyerReportsRoute: BuyerReportsRoute,
  BuyerRequestsRoute: BuyerRequestsRoute,
  BuyerSubscriptionsRoute: BuyerSubscriptionsRoute,
  BuyerNegotiationOfferIdRoute: BuyerNegotiationOfferIdRoute,
  BuyerOfferListingIdRoute: BuyerOfferListingIdRoute,
  BuyerPayOfferIdRoute: BuyerPayOfferIdRoute,
  BuyerPricesCropRoute: BuyerPricesCropRoute,
  BuyerProducerIdRoute: BuyerProducerIdRoute,
  BuyerSettingsNotifsRoute: BuyerSettingsNotifsRoute,
  BuyerSubscriptionProducerIdRoute: BuyerSubscriptionProducerIdRoute,
  BuyerPricesIndexRoute: BuyerPricesIndexRoute,
}

const BuyerRouteWithChildren = BuyerRoute._addFileChildren(BuyerRouteChildren)

interface FarmerJournalRouteChildren {
  FarmerJournalEntryIdRoute: typeof FarmerJournalEntryIdRoute
  FarmerJournalNewRoute: typeof FarmerJournalNewRoute
  FarmerJournalIndexRoute: typeof FarmerJournalIndexRoute
}

const FarmerJournalRouteChildren: FarmerJournalRouteChildren = {
  FarmerJournalEntryIdRoute: FarmerJournalEntryIdRoute,
  FarmerJournalNewRoute: FarmerJournalNewRoute,
  FarmerJournalIndexRoute: FarmerJournalIndexRoute,
}

const FarmerJournalRouteWithChildren = FarmerJournalRoute._addFileChildren(
  FarmerJournalRouteChildren,
)

interface FarmerSettingsRouteChildren {
  FarmerSettingsNotifsRoute: typeof FarmerSettingsNotifsRoute
}

const FarmerSettingsRouteChildren: FarmerSettingsRouteChildren = {
  FarmerSettingsNotifsRoute: FarmerSettingsNotifsRoute,
}

const FarmerSettingsRouteWithChildren = FarmerSettingsRoute._addFileChildren(
  FarmerSettingsRouteChildren,
)

interface FarmerRouteChildren {
  FarmerAnalyticsRoute: typeof FarmerAnalyticsRoute
  FarmerBillingRoute: typeof FarmerBillingRoute
  FarmerCommunityRoute: typeof FarmerCommunityRoute
  FarmerHomeRoute: typeof FarmerHomeRoute
  FarmerJournalRoute: typeof FarmerJournalRouteWithChildren
  FarmerPremiumRoute: typeof FarmerPremiumRoute
  FarmerReferralRoute: typeof FarmerReferralRoute
  FarmerSettingsRoute: typeof FarmerSettingsRouteWithChildren
  FarmerStorefrontRoute: typeof FarmerStorefrontRoute
  FarmerPricesCropRoute: typeof FarmerPricesCropRoute
  FarmerOrdersIndexRoute: typeof FarmerOrdersIndexRoute
  FarmerPricesIndexRoute: typeof FarmerPricesIndexRoute
}

const FarmerRouteChildren: FarmerRouteChildren = {
  FarmerAnalyticsRoute: FarmerAnalyticsRoute,
  FarmerBillingRoute: FarmerBillingRoute,
  FarmerCommunityRoute: FarmerCommunityRoute,
  FarmerHomeRoute: FarmerHomeRoute,
  FarmerJournalRoute: FarmerJournalRouteWithChildren,
  FarmerPremiumRoute: FarmerPremiumRoute,
  FarmerReferralRoute: FarmerReferralRoute,
  FarmerSettingsRoute: FarmerSettingsRouteWithChildren,
  FarmerStorefrontRoute: FarmerStorefrontRoute,
  FarmerPricesCropRoute: FarmerPricesCropRoute,
  FarmerOrdersIndexRoute: FarmerOrdersIndexRoute,
  FarmerPricesIndexRoute: FarmerPricesIndexRoute,
}

const FarmerRouteWithChildren =
  FarmerRoute._addFileChildren(FarmerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuyerRoute: BuyerRouteWithChildren,
  FarmerRoute: FarmerRouteWithChildren,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AdminKpiRoute: AdminKpiRoute,
  BatchListingIdRoute: BatchListingIdRoute,
  OnboardingBuyerRoute: OnboardingBuyerRoute,
  OnboardingFarmerRoute: OnboardingFarmerRoute,
  SSlugRoute: SSlugRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
